### ISSUE TITLE
Add support for env variables

### ISSUE THREAD

**Issue by jboesl** [dpadgett/ql-docker#3]
My server could initially not be found with the server browser because I mapped the port 30690 to 27690. Now that the port is 27690 inside and outside of the container it is listed. In docker one can pass variables to the container to start. It would be nice to be able to pass hostname, port and maybe other stuff here.

**Comment by dpadgett** [comment]
yeah there is a variable for the location part of the hostname already, but i can add more for sure.  i was thinking there could be vars for the admin steamid and hostname, port makes sense too i guess.  i made it 30960 instead of the default cuz on GCE it has to be above 30000.

**Comment by jboesl** [comment]
You might adjust the server.sh to only use default values for the ports if the vars aren't provided, yet.
I solved that the following way in the past:

```
gameport=${gameport:-'30960'}
```

This way the passed env variable is used when it is provided and 30960 otherwise.

**Comment by dpadgett** [comment]
so i think that it should work if you just do the port remapping with docker: -p 27960:30960/udp
at least i was able to then connect to my test server on port 27960 instead of 30960.  i don't think the master server cares what local port it's using as long as it's mapped externally to the right port.

**Comment by dpadgett** [comment]
thinking a bit more, given that i can just remap that way i should keep the base image using the default port and just remap to the 30000 range for GCE manually.

**Comment by jboesl** [comment]
The remapping doesn't work because the master doesn't pick it up. I can connect when I know the address, yes. But the master server can't guess the port I mapped it to.

**Comment by dpadgett** [comment]
interesting.  the master already knows how to pick up the external ip, i would think it would get the port the same way.

i can definitely put in an env var for the port.  there is no way to have that in the default EXPOSE section of the dockerfile though so you will have to manually do -p port:port/udp instead of -P.  i guess you have to do that anyway though since -P won't do udp.

**Comment by jboesl** [comment]
I think the ql-server tells the master that it is available and adds its port to the notification. The master server then picks up the address the notification comes from and the announced port.
I think you shouldn't add the EXPOSE section to the dockerfile since the port is decided on container startup and can't be backed into the image. 
Imho the best way was to adjust the server.sh to pickup the passed container variables.

**Comment by dpadgett** [comment]
doesn't hurt to keep EXPOSE i think, that is really just a hint anyway.  i just pushed fb5fe8732da16b148f4e3aee8e088efb49c4592d which adds these new vars.

**Comment by jboesl** [comment]
Yes, afaik EXPOSE is just a hint for users.
The changes look good.
